version: '3.8'
services:
  jupyter:
    user: root
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - '8888:8888'
    volumes:
      - .:/home/jovyan
    environment:
      - JUPYTER_ENABLE_LAB=True
      - CHOWN_HOME=yes
      - CHOWN_HOME_OPTS=-R
